title: week[番号] - [質問タイトル]
body:
  - type: checkboxes
    id: firstNotice
    attributes:
      label: 質問の前に確認...！
      options:
        - label: 同様の質問がすでにされていないか確認した（軽く眺めてみましょう）
    validations:
      required: true

  - type: dropdown
    id: week
    attributes:
      label: week（第何週目）のカリキュラムか
      description: weekに依存しない質問の場合はGeneralカテゴリに質問しましょう。
      options:
        - week17
        - week18
        - week19
        - week20
        - week21
        - week22
        - week23
        - week24
        - week25
        - week26
        - week27
        - week28
        - week29
        - week30
        - week31
        - week32
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: 実行環境（OS）
      description: macを使用している場合はMac OS、その他は基本的にWindowsです。
      options:
        - Mac OS
        - Windows
        - Linux
        - その他
    validations:
      required: true

  - type: textarea
    id: what_is_happening
    attributes:
      label: 現在起こっていること（説明文やエラー文、スクショなど）
      description: 分かる範囲で問題ないです！間違っていてもメンターが並走するので大丈夫です^^
    validations:
      required: true

  - type: textarea
    id: what_you_tried
    attributes:
      label: 自分で調べて試したこと
      description: どんなワードで検索したか、どんな設定を試したかなどを記入すると、回答者が状況を把握しやすくなります！
    validations:
      required: false

  - type: textarea
    id: what_you_want
    attributes:
      label: 実現したいこと
      description: ゴールが明確であればあるほど、メンターが協力しやすいです！
    validations:
      required: false

  - type: checkboxes
    id: lastNotice
    attributes:
      label: 投稿する前に確認...！
      options:
        - label: 投稿後はDiscordにも報告する
    validations:
      required: true